modLoader = "javafml"
loaderVersion = "${forgelike_loader_ver}"
license = "${license}"
issueTrackerURL = "${issue_tracker}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
logoFile = "${icon}"
authors = "${authors}"
description = '''
${description}
'''

${ dependencies_field }
